### ISSUE TITLE
training code and checkpoint

### ISSUE THREAD

**Issue by lingchuanwu** [zcong17huang/FastLFnet#1]
训练代码和训练好的权重可以提供吗

**Comment by HNU-YWB** [comment]
同求，训练代码和权重

**Comment by zcong17huang** [comment]
> 训练代码和训练好的权重可以提供吗
> 同求，训练代码和权重

非常感谢对本文章的关注，前段时间很忙碌没时间更新项目，目前已经将训练代码以及对应权重更新，谢谢！

**Comment by zcong17huang** [comment]
> 训练代码和训练好的权重可以提供吗

非常感谢对本文章的关注，前段时间很忙碌没时间更新项目，目前已将训练代码及对应权重更新，谢谢！

**Comment by zcong17huang** [comment]
> 同求，训练代码和权重

目前已将训练代码及对应权重更新，希望能够帮助到您~

**Comment by HNU-YWB** [comment]
> > 同求，训练代码和权重
> 
> 目前已将训练代码及对应权重更新，希望能够帮助到您~

非常感谢！祝大佬论文产量节节高！
