### ISSUE TITLE
训练的一些小问题

### ISSUE THREAD

**Issue by HNU-YWB** [zcong17huang/FastLFnet#2]
![image](https://user-images.githubusercontent.com/48237899/159260760-76309096-538c-49bb-8de9-0e7938a1b7fb.png)
请问在训练时这个3出现了错误index 3 is out of bounds for axis 2 是什么原因呢，有点没看懂这个语句的意思，恳请大佬解答，感谢！

**Comment by zcong17huang** [comment]
我想您应该是忘记加上EPINet文章中所提到的反射区域Mask，详见[EPINet](https://github.com/chshin10/epinet/tree/master/hci_dataset/additional_invalid_area)

**Comment by HNU-YWB** [comment]
> 我想您应该是忘记加上EPINet文章中所提到的反射区域Mask，详见[EPINet](https://github.com/chshin10/epinet/tree/master/hci_dataset/additional_invalid_area)

好的好的，我去学习一下！确实是没啥印象了，感谢您！
