### ISSUE TITLE
codeStep1 训练无法启动的问题

### ISSUE THREAD

**Issue by HNU-YWB** [zcong17huang/FastLFnet#3]
您好，不好意思又来打扰了，我按照您readme的步骤进行训练，输入命令：
 python train.py --epochs 1000 --datapath D:\pycharm\light-field-depth\FastLFnet-main\dataset --savemodel D:\pycharm\light-field-depth\FastLFnet-main\demo --nums 9 --maxdisp 16 

程序没有报错但是一直卡在第一步没有往下进行，如图示：
![1647933239](https://user-images.githubusercontent.com/48237899/159427334-f5885077-1ee3-479d-b523-61c7817beea0.jpg)
![1647933239(1)](https://user-images.githubusercontent.com/48237899/159427345-0d749c52-3bb8-4af1-9e18-82f5dcd2c33d.jpg)

我只改动了dataloader的num_workers=4,请问您是否遇到过这样的问题？感谢您的解答！

**Comment by doubiydd** [comment]
还有一个问题就是，readme写到使用数据集中的additional作为训练，其他数据作为测试，请问在train代码里是否要将训练集路径定位到additional文件夹呀，谢谢！

**Comment by doubiydd** [comment]
> 还有一个问题就是，readme写到使用数据集中的additional作为训练，其他数据作为测试，请问在train代码里是否要将训练集路径定位到additional文件夹呀，谢谢！

这个问题我在listLFfile看到了！

**Comment by HNU-YWB** [comment]
救救孩子，一直在第0步训练卡住。。。是不是因为我用的windows有关...

**Comment by zcong17huang** [comment]
> 救救孩子，一直在第0步训练卡住。。。是不是因为我用的windows有关...

您可以在任务管理器看看CPU、GPU占用情况，我的印象里，用windows的时候好像刚开始加载数据会比较慢

**Comment by doubiydd** [comment]
![image](https://user-images.githubusercontent.com/48237899/159647174-157c48ec-72a3-4b1f-8215-cc9e9cc482d5.png)
基本占用率都是这样，GPU基本没反应，因为windows好像对dataloader的支持不太好，多进程容易崩，我超过4的num_workers都会报错BrokenPipeError: [Errno 32] Broken pipe，但是第一步有一次一直等了五六个小时都没有反应，我的CPU是I7-10700K，显卡是2060S（8G显存），python3.7+torch1.9.0+cuda11.1.。。不知道是不是windows的问题

**Comment by HNU-YWB** [comment]
> > 救救孩子，一直在第0步训练卡住。。。是不是因为我用的windows有关...
> 
> 您可以在任务管理器看看CPU、GPU占用情况，我的印象里，用windows的时候好像刚开始加载数据会比较慢

基本占用率都是这样，GPU基本没反应，因为windows好像对dataloader的支持不太好，多进程容易崩，我超过4的num_workers都会报错BrokenPipeError: [Errno 32] Broken pipe，但是第一步有一次一直等了五六个小时都没有反应，我的CPU是I7-10700K，显卡是2060S（8G显存），python3.7+torch1.9.0+cuda11.1.。。不知道是不是windows的问题
![image](https://user-images.githubusercontent.com/48237899/159647878-d5c6b243-bbd4-495d-b2bf-09203f6f78eb.png)
![image](https://user-images.githubusercontent.com/48237899/159647918-4263f3f0-6cb4-41ca-affe-4418c357465a.png)

**Comment by zcong17huang** [comment]
> > > 救救孩子，一直在第0步训练卡住。。。是不是因为我用的windows有关...
> > 
> > 
> > 您可以在任务管理器看看CPU、GPU占用情况，我的印象里，用windows的时候好像刚开始加载数据会比较慢
> 
> 基本占用率都是这样，GPU基本没反应，因为windows好像对dataloader的支持不太好，多进程容易崩，我超过4的num_workers都会报错BrokenPipeError: [Errno 32] Broken pipe，但是第一步有一次一直等了五六个小时都没有反应，我的CPU是I7-10700K，显卡是2060S（8G显存），python3.7+torch1.9.0+cuda11.1.。。不知道是不是windows的问题 ![image](https://user-images.githubusercontent.com/48237899/159647878-d5c6b243-bbd4-495d-b2bf-09203f6f78eb.png) ![image](https://user-images.githubusercontent.com/48237899/159647918-4263f3f0-6cb4-41ca-affe-4418c357465a.png)

GPU您可以在3D那边的下拉菜单里，看看CUDA。正常来说，应该刚开始读取数据的时候，硬盘占用量比较高；然后因为对数据处理比较多，cpu占用率比较高。您可以debug一下看看程序卡在哪里了

**Comment by HNU-YWB** [comment]
> > > > 救救孩子，一直在第0步训练卡住。。。是不是因为我用的windows有关...
> > > 
> > > 
> > > 您可以在任务管理器看看CPU、GPU占用情况，我的印象里，用windows的时候好像刚开始加载数据会比较慢
> > 
> > 
> > 基本占用率都是这样，GPU基本没反应，因为windows好像对dataloader的支持不太好，多进程容易崩，我超过4的num_workers都会报错BrokenPipeError: [Errno 32] Broken pipe，但是第一步有一次一直等了五六个小时都没有反应，我的CPU是I7-10700K，显卡是2060S（8G显存），python3.7+torch1.9.0+cuda11.1.。。不知道是不是windows的问题 ![image](https://user-images.githubusercontent.com/48237899/159647878-d5c6b243-bbd4-495d-b2bf-09203f6f78eb.png) ![image](https://user-images.githubusercontent.com/48237899/159647918-4263f3f0-6cb4-41ca-affe-4418c357465a.png)
> 
> GPU您可以在3D那边的下拉菜单里，看看CUDA。正常来说，应该刚开始读取数据的时候，硬盘占用量比较高；然后因为对数据处理比较多，cpu占用率比较高。您可以debug一下看看程序卡在哪里了

![image](https://user-images.githubusercontent.com/48237899/159649215-365fe5f3-1e97-4c3e-bd46-4831d8b80776.png)
CUDA占用率是0...
程序应该是卡在train.py的150行这里一直没往下进行了。我看看能不能debug找到问题吧，不行的话只能换到ubuntu环境再试试了
![image](https://user-images.githubusercontent.com/48237899/159649480-71f589b1-f776-44a9-bb55-95d1c09d268b.png)

**Comment by HNU-YWB** [comment]
> > > > 救救孩子，一直在第0步训练卡住。。。是不是因为我用的windows有关...
> > > 
> > > 
> > > 您可以在任务管理器看看CPU、GPU占用情况，我的印象里，用windows的时候好像刚开始加载数据会比较慢
> > 
> > 
> > 基本占用率都是这样，GPU基本没反应，因为windows好像对dataloader的支持不太好，多进程容易崩，我超过4的num_workers都会报错BrokenPipeError: [Errno 32] Broken pipe，但是第一步有一次一直等了五六个小时都没有反应，我的CPU是I7-10700K，显卡是2060S（8G显存），python3.7+torch1.9.0+cuda11.1.。。不知道是不是windows的问题 ![image](https://user-images.githubusercontent.com/48237899/159647878-d5c6b243-bbd4-495d-b2bf-09203f6f78eb.png) ![image](https://user-images.githubusercontent.com/48237899/159647918-4263f3f0-6cb4-41ca-affe-4418c357465a.png)
> 
> GPU您可以在3D那边的下拉菜单里，看看CUDA。正常来说，应该刚开始读取数据的时候，硬盘占用量比较高；然后因为对数据处理比较多，cpu占用率比较高。您可以debug一下看看程序卡在哪里了

![image](https://user-images.githubusercontent.com/48237899/159663741-76b2b7e4-906a-441b-89d1-b8f00747e3f4.png)
debug后发现就是计算损失函数这里进行不下去了，我换了CPU训练没用CUDA结果也是一样的，一直卡在这里。。。同时换了另外一台电脑用了num_workers=8也不行。。同样也是卡在这里，按理说光场4DHCI数据集不应该读取需要这么久吧。。。本菜鸡真是菜麻了OTZ
