### ISSUE TITLE
关于训练卡住debug后的一些问题

### ISSUE THREAD

**Issue by HNU-YWB** [zcong17huang/FastLFnet#4]
昨天调试了一通程序，发现程序卡在下图中语句没有往下进行，初步猜测可能是数据读取有问题，遍历程序发现某些地方的数据设置和现有数据集不同，请问下作者大大是否数据集后期做了更新，可否更新一下您的数据设置方式或者在github中更新dataset呀，感谢感谢！（打扰多次非常不好意思）
![Uploading image.png…]()

**Comment by HNU-YWB** [comment]
![image](https://user-images.githubusercontent.com/48237899/159859480-1a27b56b-96cc-4975-ac5f-98aa7ee8781a.png)

**Comment by HNU-YWB** [comment]
问题解决了！其实是一开始没有加上epinet的mask区域导致的程序无法进行！感谢作者大大最开始的指点！

**Comment by zcong17huang** [comment]
> 问题解决了！其实是一开始没有加上epinet的mask区域导致的程序无法进行！感谢作者大大最开始的指点！

解决了就好，您客气了，祝一切顺利！
