### ISSUE TITLE
关于codeStep2训练的一点小问题

### ISSUE THREAD

**Issue by HNU-YWB** [zcong17huang/FastLFnet#5]
作者大大，在codeStep2训练时发现HCIloader中有一个
edge_name = os.path.join(LF_dir, 'BinaryEdge.png')
我在官方数据集和EPI数据集的这个路径中都没有找到这个图片文件，请问您这是在哪一步生成的嘛或者我哪一步漏了什么关键步骤嘛，谢谢解答！
![a5a91c3bbb11875080a2e5a2063cce5](https://user-images.githubusercontent.com/48237899/160040387-14672889-a83f-4dc1-913b-607610d23a37.jpg)
![fc7ce95256e029c04c598cf347266e5](https://user-images.githubusercontent.com/48237899/160040397-3ee2dc46-07e7-4e9a-8d49-32d6b050ab15.jpg)

**Comment by HNU-YWB** [comment]
会不会是文件名命名的问题呢，我新下载的数据集中显示是这样的
![image](https://user-images.githubusercontent.com/48237899/160072063-8ee1b9ca-48c0-4620-879b-ade0ba96dd82.png)

**Comment by HNU-YWB** [comment]
或者是不是需要先用sobel算法单独对每一种图像数据的中间图像进行边缘提取后再放入数据集中，同时分辨率需要满足5120*5120呢？@zcong17huang

**Comment by zcong17huang** [comment]
> 或者是不是需要先用sobel算法单独对每一种图像数据的中间图像进行边缘提取后再放入数据集中，同时分辨率需要满足5120*5120呢？@zcong17huang

您好，之前因为疏忽忘记上传数据集的边缘图，现在已经上传[边缘图](https://github.com/zcong17huang/FastLFnet#edge-maps)，请将其放入对应数据集中使用，谢谢~

**Comment by HNU-YWB** [comment]
> > 或者是不是需要先用sobel算法单独对每一种图像数据的中间图像进行边缘提取后再放入数据集中，同时分辨率需要满足5120*5120呢？@zcong17huang
> 
> 您好，之前因为疏忽忘记上传数据集的边缘图，现在已经上传[边缘图](https://github.com/zcong17huang/FastLFnet#edge-maps)，请将其放入对应数据集中使用，谢谢~

好的谢谢您！我自己用sobel算法全部对中心图片做了一次边缘提取hhh感谢感谢
