### ISSUE TITLE
About the One scale model problem?

### ISSUE THREAD

**Issue by dreamhua82** [zcong17huang/FastLFnet#6]
HI, what is the one Scale model in Table 2? How do you construct the One scale model?
Can you share the One scale model code ?
Thks.

**Comment by zcong17huang** [comment]
Thank you for your attention. As for One Scale model, we use the maximum disaprity range(maxdisp=16) for all views to construct cost volumes. So for all cost volumes, their D in the dimension(B×D×H×W) is the same. And then we use 2×`SimpleBottleneck`(corresponding [code](https://github.com/zcong17huang/FastLFnet/blob/31d36ad6a8403563d55bdda632cb70b9bd377e0e/codeStep3/models/submodule.py#L42)) + `volumegate`(corresponding [code](https://github.com/zcong17huang/FastLFnet/blob/31d36ad6a8403563d55bdda632cb70b9bd377e0e/codeStep3/models/aggregation.py#L134)) + 4×`SimpleBottleneck` for aggregation. I'm really sorry that I can't find the code. I hope my description can help you.

**Comment by dreamhua82** [comment]
Hi, Sorry for trouble you. 
what is 'all views' mean? 17 views in horizontal and vertical EPI  or 81 views?
maxdisp range means D ==33?

**Comment by zcong17huang** [comment]
> Hi, Sorry for trouble you. what is 'all views' mean? 17 views in horizontal and vertical EPI or 81 views? maxdisp range means D ==33?

Yes, the input view (2-streams) and the channel number of features (16) have been selected in Table 1. For maxdisp=16, D is 33 as you said.
