### ISSUE TITLE
where is 'additional_invalid_area' ?

### ISSUE THREAD

**Issue by Gardlin** [zcong17huang/FastLFnet#7]
Hi, Thanks for your great work.

However, when I run codestep1 python train.py , it went wrong with this line
https://github.com/zcong17huang/FastLFnet/blob/31d36ad6a8403563d55bdda632cb70b9bd377e0e/codeStep1/train.py#L81
It  seems that I didn't  have this image，Do I  download the wrong dataset of kitchen scene? I only have  additional  folder  data, but not additional_invalid_area  and  input_cam040_invalid_ver.png

**Comment by zcong17huang** [comment]
> Hi, Thanks for your great work.
> 
> However, when I run codestep1 python train.py , it went wrong with this line
> 
> https://github.com/zcong17huang/FastLFnet/blob/31d36ad6a8403563d55bdda632cb70b9bd377e0e/codeStep1/train.py#L81
> 
> 
> It seems that I didn't have this image，Do I download the wrong dataset of kitchen scene? I only have additional folder data, but not additional_invalid_area and input_cam040_invalid_ver.png

I think you forgot the mask of reflection areas, the same as [Issue 2](https://github.com/zcong17huang/FastLFnet/issues/2). Please reference to [EPINet](https://github.com/chshin10/epinet/tree/master/hci_dataset/additional_invalid_area). Thanks a lot.
